### ISSUE TITLE
Suggestion: Story settings

### ISSUE THREAD

**Issue by Muskelmagier** [cloveranon/Clover-Edition#101]
We really need a better explanation for which settings do what.
As someone who doesn't has any deeper knowledge about the cooding part some setting don't make any sense to me or are only poorly explained in their short descriptions.

example: 

- top-keks           Number of words the AI can randomly choose
- temp               Higher values make the AI more random

what are the differences with them in story output context?

what could be done to fix this:
how about a few preset suggestions option for different story types like bundling them together for a preset for more focused stories with less random encounter.

**Comment by devfag** [comment]
The OpenCYOAI wiki gives a fairly decent explanation, although even that is a simplification and doesn't fully explain the nuances of the values: https://github.com/OpenCYOAI/OpenCYOAI/wiki/A-quick-explanation-on-what-is-top_k,-temp-and-top_p

As for presets, unfortunately it doesn't work that cleanly; two different stories in the same genre or style could still have entirely different results at the same `temp` and `top_k` value. It's all a matter of the information you give the AI and the data the AI has been trained on.

Hope this helps.
