### ISSUE TITLE
Colorama not working for input line in Powershell

### ISSUE THREAD

**Issue by K1ll3rM** [cloveranon/Clover-Edition#102]
The Python Colorama package doesn't seem to work with the input line though it works fine for all other lines.
In Powershell:
![image](https://user-images.githubusercontent.com/24224847/71997985-141d1480-323f-11ea-9b94-5a6ae6ebac29.png)

**Comment by devfag** [comment]
Try enabling ANSI Terminal Control in Windows: https://superuser.com/a/1300251

**Comment by cloveranon** [comment]
I don't know why it doesn't work with python's input function prompt. I believe a simple solution is just to print the prompt without a newline (`end=''`) and then ask for input.

**Comment by Meanmelter** [comment]
I located a possible fix for this

`import ctypes
    kernel32 = ctypes.windll.kernel32
    kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)`

Testing now
