### ISSUE TITLE
Is it possible: Retrying during prompt generation

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#109]
I might like a possibility to have regular expressions applied to words or whole sentences that would make the AI retry generating a new output (at most a few times, after which the player has to try a different input). However, if the AI has to generate all the 80 tokens before applying these rules, it will be horrifically slow on a CPU. So really, to make this more viable, the retrying would have to happen partway through the generation of output. And maybe even only regenerate the output partially; so probably just the sentence in which the blacklisted regular expression appeared.

I probably understand quite little about gpt2generator.py so I don't think I should attempt such a modification. I did identify that the "main action" happens in sample_sequence. What it generates is currently not human-readable at all, and I think is decoded by self.tokenizer.decode in one fell swoop with the default settings. But would it be a huge performance penalty (or could it even be done) to apply the decoder to individual tokens right after they are generated?

**Comment by Akababa** [comment]
This is actually possible thanks to the imperative nature of pytorch (it's the same way it stops generation on end tokens [here](https://github.com/cloveranon/Clover-Edition/blob/20561d1f8d01969e8d5d879085c1cd493db0f565/gpt2generator.py#L152)). To apply a normal regex you'd have to decode the output on every step of that loop, which shouldn't incur much performance penalty.

**Comment by MikkoMMM** [comment]
Well, we'll see if I decide to try to implement this feature. I can't promise it won't be spaghetti code but who knows if it will be borderline usable.
