### ISSUE TITLE
[FEAT] Add Alter, Context, remember, and retry commands.

### ISSUE THREAD

**Issue by Meanmelter** [cloveranon/Clover-Edition#11]
Pulled from thadung2
##########
_alter                    Edit the most recent AI response
context               Edit what your AI has currently committed to memory.
remember XXX   Commit something important to the AI\'s memory for that session.
retry                   Reverts the last action and tries again with the same action._
##########```

                elif command == 'remember':
                    if len(args) == 0:
                        console_print("Failed to add to memory. Example usage: /remember that Sir Theo is a knight")
                    else:
                        story_manager.story.context += "You know " + " ".join(args[0:]) + ". "
                        console_print("You make sure to remember {}.".format(" ".join(action.split(" ")[1:])))
                    
                elif command == 'retry':

                    if len(story_manager.story.actions) is 0:
                        console_print("There is nothing to retry.")
                        continue

                    last_action = story_manager.story.actions.pop()
                    last_result = story_manager.story.results.pop()

                    try:
                        try:
                            story_manager.act_with_timeout(last_action)
                            console_print(last_action)
                            console_print(story_manager.story.results[-1])
                        except FunctionTimedOut:
                            console_print("That input caused the model to hang (timeout is {}, use infto ## command to change)".format(story_manager.inference_timeout))
                            if ping:
                                playsound('ping.mp3')
                    except NameError:
                        pass
                    if ping:
                        playsound('ping.mp3')

                    continue

                elif command == 'context':
                    try:
                        current_context = story_manager.get_context()
                        console_print("Current story context: \n")
                        new_context = string_edit(current_context)
                        if new_context is None:
                            pass
                        else:
                            story_manager.set_context(new_context)
                            console_print("Story context updated.\n")
                    except:
                        console_print("Something went wrong, cancelling.")
                        pass

                elif command == 'alter':
                    try:
                        console_print("\nThe AI thinks this was what happened:\n")
                        try:
                            current_result = story_manager.story.results[-1]
                        except IndexError:
                            current_result = story_manager.story.story_start
                        new_result = string_edit(current_result)
                        if new_result is None:
                            pass
                        else:
                            try:
                                story_manager.story.results[-1] = new_result
                            except IndexError:
                                story_manager.story.story_start = new_result
                            console_print("Result updated.\n")
                    except:
                        console_print("Something went wrong, cancelling.")
                        pass
```

**Comment by cloveranon** [comment]
What exactly is `string_edit`? That's an interesting function.

**Comment by cloveranon** [comment]
Huh they have implemented their own command line text editor to do this: [thadunge2/AIDungeon/story/utils.py](https://github.com/thadunge2/AIDungeon/blob/c198371c34d914e9d996559ef850c87a76f572c4/story/utils.py)

**Comment by nii236** [comment]
The `/altergen` command is great too.

https://github.com/thadunge2/AIDungeon/issues/40

Available in: https://henk.tech/aid/

It basically allows you to /alter the previous snippet, but the AI actually adds onto it for you as well!

**Comment by devfag** [comment]
added `/alter` and `/prompt`, which is /alter for the permanent paragraph. i'll add `/remember` and an equivalent command for removing things from memory today

**Comment by MikkoMMM** [comment]
There is an implementation of /remember in the Python Prompt Toolkit branch which isn't dependant on that library: https://github.com/cloveranon/Clover-Edition/blob/prompt-toolkit/play.py

But there might always be a smarter implementation.

**Comment by AtaIanta** [comment]
If I read code correctly then /remember will not work on colab with prompt toolkit so it needs another way of implementation just for colab users

**Comment by MikkoMMM** [comment]
Really? I think that every type of call in that part is used somewhere else in Clover's master already (and if TOOLKIT_ENABLED is False, the command should work still with the old colPrint too). So which part exactly would be problematic in your view?

**Comment by AtaIanta** [comment]
Huh I was dumb and thought /remember needed toolkit set to true, nvm

**Comment by Meanmelter** [comment]
From what I can tell, all of these features have been added.
The only difference is that `/Context` is now `/prompt` (Could even just setup an alias.)
If there is an issue with one of the commands, either by not working on colab or they break entirely, I say we should create a new issue as it would be out of scope for this enhancement.

Thanks guys for the hard work; Wish I could have done more to help with these.
