### ISSUE TITLE
You is stripped in Colab mode

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#110]
I wrote: > You test

It at least output as the "final prompt": > test.

**Comment by devfag** [comment]
Is prompt toolkit turned on even though you're in colab? Make sure it's disabled.

**Comment by MikkoMMM** [comment]
It was. So, the in_colab() is missing a line
`settings["prompt-toolkit"] = "off"`
for the case that `settings.getboolean("colab-mode")` returns true.

**Comment by MikkoMMM** [comment]
Or another way to interpret this: the play.py shouldn't ask for `if not settings.getboolean("prompt-toolkit")` directly, but the use_ptoolkit() function like all the cool functions do.

**Comment by MikkoMMM** [comment]
I suppose I should mention that this is fixed in PR https://github.com/cloveranon/Clover-Edition/pull/111.

**Comment by devfag** [comment]
Just a tip: you can type `closes #111` in the description of the PR and it will automatically close this issue when the pr is merged
