### ISSUE TITLE
Model Distribution

### ISSUE THREAD

**Issue by Rioghasarig** [cloveranon/Clover-Edition#114]
So I was thinking that there could be other ways to distribute the model than via torrents. I set a up a google cloud bucket containing the model for people to access. 

Link: https://storage.googleapis.com/clover-edition/model_v5_pytorch.zip

Right now it's up for anyone to download easily by just clicking the links. I'm currently paying the costs but it's pretty reasonable as long as only a few thousand people download it (though I doubt that will happen). If the downloads get too much though it will be taken down, but I have an alternative solution that will only require a little bit more work on the part of the downloaders  to access it. (This involves making use of the 'requester-pays' option of the google storage buckets). I think this is a better solution for hosting a variety of different models, rather than seeding a bunch of different torrents.

**Comment by Akababa** [comment]
Awesome, can you also host the 16bit model? I have a copy on my google drive at https://drive.google.com/drive/folders/1ALBdqhctniyg4UKVHKdFVA8MPT2ZprpQ?usp=sharing

**Comment by Rioghasarig** [comment]
Yeah, I'll do that. 

But I'm noticing a problem. There's a different charge depending of if you download it "within" the US ($.01 / GB) vs outside ($.12 / GB). I tested it right now and even though I'm within the US its charging me the higher cost. This may be just because I had some settings wrong but if I can't fix it  this may limit the ability to access the files as a simple link. 

However, it still feasible to host the cloud on google cloud storage. But it will require people to sign up for google cloud and use some of the cloud platform tools. This can make it so the downloader can pay the network costs instead of me. That's probably what will happen if this gets really popular.

**Comment by Akababa** [comment]
Damn yea it might have hit the download quota already, maybe try again tomorrow. I've been meaning to get a torrent up and running but it's tough seeding from my laptop and I don't know of any torrents of the 16bit model.

**Comment by Rioghasarig** [comment]
I got the 16-bit model too. It should be available at: 

https://storage.googleapis.com/clover-edition/model_v5_pytorch_16-bit.zip

And again Europeans should replace 'clover-edition' with 'clover-europe'.

**Comment by Skhmt** [comment]
None of these links are still available.
