### ISSUE TITLE
Changing of name?

### ISSUE THREAD

**Issue by DonaldTsang** [cloveranon/Clover-Edition#117]
As addresed in https://github.com/thadunge2/AIDungeon/issues/60 and https://github.com/VBPXKSMI/Open-CYOAI-Project/issues/144 the original code is going to become a proprietary thing, so it might be a good idea for the community to rename it to something else that is consistent.

I would suggest "oubliette" or some synonym of dungeon.

**Comment by Skhmt** [comment]
Will revisit if it becomes legally necessary.
