### ISSUE TITLE
New Training Approach

### ISSUE THREAD

**Issue by Rioghasarig** [cloveranon/Clover-Edition#125]
So Microsoft just came out with this new 'Zero Redundancy Optimizer'. It makes training large neural networks more efficient.  They even analyze the training capacity of GPT2

https://github.com/microsoft/DeepSpeed/blob/master/docs/tutorials/MegatronGPT2Tutorial.md

Looking at the 'Low Bandwidth GPU Cluster'  they claim that their Zero Redundancy Optimizer can train the 1.5B GPT2 without model parallelism on a GPU with 16 GB memory. This should make training GPT2 much more feasible on AWS p3 instances. 

I've been wanting to try and finetune the full model further but have been having trouble getting a good set up . This is definitely a big help.

**Comment by Skhmt** [comment]
Stale, link no longer works.
