### ISSUE TITLE
Latest version of the distributable "Transformers" doesnt work

### ISSUE THREAD

**Issue by ComputerFox** [cloveranon/Clover-Edition#127]
Not very coding-savvy, but I wanted to give a heads up on this. While I was installing this I had been getting an import error from 'transformers.modeling_gpt2' on running the play.py, I went to check and it seems to refer to a gelu_new.
Running "pip install transformers==2.3.0" seemed to fix it if anyone else had issues with this, it may be useful to amend the install instructions with this in mind as I feel as though I only stumbled upon the fix by chance, though im not sure if version 2.4.0 works as well, I just know that 2.5.0 doesnt work.

**Comment by MikkoMMM** [comment]
Well, the installation instructions probably could use an update. I haven't dared touch them myself but I believe that the individual package installation instructions could be replaced with just:
`pip install -r requirements.txt`

**Comment by AIDungeonWiXAnon** [comment]
Agreed, definitely needs an update; it's certainly not uncommon for ML frameworks/libraries to not be backward-compatible, and while our requirements.txt is rather explicit in specifying 2.3 the install instructions simply pull whatever the latest released version of transformers happens to be.

Strange that we don't direct users to install dependencies via requirements.txt to begin with, really. But at any rate I'll update the instructions now to install 2.3.
