### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by NyxNyxNyxNyxNyxNyx** [cloveranon/Clover-Edition#129]
Trying to execute play.py gives this error:

Traceback (most recent call last):
  File "C:\Users\XXXX\Downloads\AID\AID2 Clover Edition\play.py", line 14, in <module>
    from gpt2generator import GPT2Generator
  File "C:\Users\XXXX\Downloads\AID\AID2 Clover Edition\gpt2generator.py", line 7, in <module>
    from gpt2 import GPT2LMHeadModel
  File "C:\Users\XXXX\Downloads\AID\AID2 Clover Edition\gpt2.py", line 5, in <module>
    from transformers.modeling_gpt2 import load_tf_weights_in_gpt2, gelu, GPT2PreTrainedModel
ImportError: cannot import name 'gelu' from 'transformers.modeling_gpt2' (C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\modeling_gpt2.py)

**Comment by MikkoMMM** [comment]
I recently had a problem launching as well, having to do with a wrong version of a library. Let's confirm you've got the right version of transformers at least (it should be 2.3.0).

Run the Python 3.7 interpreter (with the same command you used to run play.py) and run the commands:
```
import transformers
print(transformers.__version__)
```

And exit by: exit()
(Hopefully it works the same way on Windows as it does on Linux.)

**Comment by MikkoMMM** [comment]
The solution is:
```
pip uninstall transformers
pip install transformers==2.3.0
```
