### ISSUE TITLE
Choosing a suggested action without erasing You leads to the action being a number

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#130]
I have in the config:
action-sugg = 1
colab-mode = off
prompt-toolkit = on

And when I try to select "You 0" as my action, it outputs as the finalized action:
`> You 0.`
instead of selecting the suggested action. However, just "0" works correctly.

**Comment by AIDungeonWiXAnon** [comment]
Looks like this is being caused by conditionals not being tied together correctly and overriding each other. Should be a quick fix after a bit of testing!
