### ISSUE TITLE
ImportError: cannot import name 'gelu' from 'transformers.modeling_gpt2'

### ISSUE THREAD

**Issue by bell117** [cloveranon/Clover-Edition#132]
I installed Ai Dungeon with the auto-installer except I cannot launch it as when I type "python play.py" or "play.py" into the command line I'm met with this error:
Traceback (most recent call last):
  File "play.py", line 14, in <module>
    from gpt2generator import GPT2Generator
  File "gpt2generator.py", line 7, in <module>
    from gpt2 import GPT2LMHeadModel
  File "gpt2.py", line 5, in <module>
    from transformers.modeling_gpt2 import load_tf_weights_in_gpt2, gelu, GPT2PreTrainedModel
ImportError: cannot import name 'gelu' from 'transformers.modeling_gpt2' (modeling_gpt2.py)

How do I fix this error?(I removed the file locations from the lines so ignore that bit)

**Comment by MikkoMMM** [comment]
So, there probably is something going on with the installer since the issue has come up before: https://github.com/cloveranon/Clover-Edition/issues/129

The installers are maintained separately, but I might have found the issue. https://github.com/AIDungeonWiXAnon/AID2-Installer-Project/blob/master/AID2%20Clover%20Edition%20Installer%20Beta/CustomCommands.wxs

Clover requires transformers==2.3.0, and on those CustomCommands no specific version is given. Try:
```
pip uninstall transformers
pip install transformers==2.3.0
```

And maybe post a ticket on the installer's GitHub page.

**Comment by bell117** [comment]
> So, there probably is something going on with the installer since the issue has come up before: #129
> 
> The installers are maintained separately, but I might have found the issue. https://github.com/AIDungeonWiXAnon/AID2-Installer-Project/blob/master/AID2%20Clover%20Edition%20Installer%20Beta/CustomCommands.wxs
> 
> Clover requires transformers==2.3.0, and on those CustomCommands no specific version is given. Try:
> 
> ```
> pip uninstall transformers
> pip install transformers==2.3.0
> ```
> 
> And maybe post a ticket on the installer's GitHub page.

That seems to have fixed the current issue and was able to get to the initialisation screen where I got the new error "RuntimeError: CUDA out of memory" as well as "line 767, in <module>
    if gm and gm.story:
NameError: name 'gm' is not defined"

**Comment by MikkoMMM** [comment]
I believe that it's trying to utilize your graphics card but at least the error message sounds like it's encountering insufficient VRAM. Here's what the README says about the requirement:

> The original model has 1558 Million Parameters. It is 5.9GiB and requires >8GB of VRAM to run normally on a GPU and >4GB of VRAM to run at our reduced 16 bit mode.
> 
> It is possible to play on a GPU with less than 4GB of VRAM with smaller models. Many anons have trained smaller models (see the section on Finetuning). We need volunteers to convert other models to pytorch and create torrents for them.

Though, I've encountered 12 GB to be said to be the recommended amount for the tensorflow versions of AID2, so half of that would result in a 6 GB as a recommendation for Clover.

There is a setting for forcing Clover Edition to utilize CPU instead. In config.ini, edit the line
force-cpu = off
to say
force-cpu = on

Note that running on a CPU is tremendously slower, but if it must be so then it's possible.

**Comment by bell117** [comment]
VRAM shouldn't be an issue since I have a GTX 1650 with >4GB VRAM, I'll still try to run it off my CPU anyways.

**Comment by MikkoMMM** [comment]
Well, the issue in the name of the ticket was solved at least. I'll report it to the installer project.

**Comment by Akababa** [comment]
We can probably monkey patch this in too, by coping the code from gelu into this repo.

**Comment by MikkoMMM** [comment]
Clover appears to be MIT while transformers is Apache licensed. But there are instructions on how to copy code from one to the other: https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered

But then there's also a gelu_new function. How would that change things if we were to allow its usage?

**Comment by Akababa** [comment]
I think the gelu function itself might be okay to copy over, because it originally came from arxiv. And we can always write our own gelu function from scratch in a couple lines; in fact that's probably what I'll do.

**Comment by Akababa** [comment]
FYI I just pushed https://github.com/cloveranon/Clover-Edition/commit/90dfaa701b49ec954da66031a1d5f51e14ad4992 which replaces transformers gelu with our own.
