### ISSUE TITLE
hackyWhiteSpaceCutter() only returns only trailing whitespace

### ISSUE THREAD

**Issue by BrittleSalsa** [cloveranon/Clover-Edition#134]
I noticed that in the HackyWhiteSpaceCutter
https://github.com/cloveranon/Clover-Edition/blob/c9f0a0fbabf227c81226a70887be18f30bde4d9a/gpt2generator.py#L38-L39

Used here:
https://github.com/cloveranon/Clover-Edition/blob/c9f0a0fbabf227c81226a70887be18f30bde4d9a/gpt2generator.py#L49

the regex matches whitespace at the end of input, so what this does is take just the trailing whitespace from the prompt and prepend that whitespace to the context.

Just wondering if this is deliberate? When I first read line 49, I thought the intention was to prepend a cleaned up version of the prompt to the context, but that's actually done later, here:

https://github.com/cloveranon/Clover-Edition/blob/c9f0a0fbabf227c81226a70887be18f30bde4d9a/gpt2generator.py#L52-L53

My suspicion is we should just remove hackyWhiteSpaceCutter completely and have 
`context_tokens = hackyEncode(tokenizer, context)`

**Comment by Skhmt** [comment]
Confirmed and fixed.

**Comment by cloveranon** [comment]
It preserves whitespace the user enters.
