### ISSUE TITLE
prompt is saying torch module is missing, even though I had installed torch

### ISSUE THREAD

**Issue by thunderheart396** [cloveranon/Clover-Edition#135]
So, I've made multiple attempts at setting the game up. Uninstalling python and everything, reinstalling it, making sure and double-checking it's all set up. I even tried the batch installer. But, for some reason, it's not finding the pytorch module anywhere. I'm not changing the install location of Torch or Python or anything. It's just not finding it.

![but torch is installed](https://user-images.githubusercontent.com/45987388/82712598-5aa36680-9c56-11ea-9610-105c7c542e6c.PNG)

**Comment by Akababa** [comment]
try `pip install torch`?

**Comment by Meanmelter** [comment]
What version of Windows are you using?

**Comment by Glendening** [comment]
This was a giant PITA for me. Try "python play.py" without the " marks If that doesn't work I think I used "conda install pytorch" to get the newest one

**Comment by SpaceCowboy3514** [comment]
I am still having this issue and python play.py results in 
Model could not be loaded. Please try another model.
02/13/2021 22:10:23 - INFO - Using model: models\pytorch-gpt2-xl-aid2-v5
02/13/2021 22:10:23 - INFO - Using device=cuda, checkpoint=models\pytorch-gpt2-xl-aid2-v5, dtype=torch.float16
endlessly

**Comment by Skhmt** [comment]
Did you install a model?

**Comment by Skhmt** [comment]
Stale - Open a new issue if you're still having problems.

Make sure you actually have a model.
