### ISSUE TITLE
Disabling suggestions 

### ISSUE THREAD

**Issue by Nalewa** [cloveranon/Clover-Edition#14]
So I tried disabling suggestions by setting in config
`action-alternatives = 0`
and got this
```
Traceback (most recent call last):
  File "play.py", line 333, in <module>
    play(generator)
  File "play.py", line 245, in play
    if action in [str(i) for i in range(len(suggested_actions))]:
UnboundLocalError: local variable 'suggested_actions' referenced before assignment
```
You can generate story but it crashes after typing action.

**Comment by AccidentallyOnPurpose** [comment]
Nice, catch. commit 6cca6b4 should fix it

**Comment by Meanmelter** [comment]
I tested this fix. It seems act_alts is not defined.
![image](https://user-images.githubusercontent.com/17638040/71439097-40288980-26c6-11ea-8745-e162b20c15be.png)

**Comment by Nalewa** [comment]
change line 244 to 
`                if settings.getint('action-alternatives') > 0:`

**Comment by AccidentallyOnPurpose** [comment]
Shit sorry... fixed... tested... pushed.  I need to work on branches and test more. No more master changes for a while.

BTW there is a `new_suggestions_with_context` branch where 2 suggestion are based on some of the story, and 2 are pretty random. You might want to try it some time.

**Comment by Meanmelter** [comment]
I will try that one for you tomorrow @AccidentallyOnPurpose 
I am going to be sleeping soon though, so I will have to provide input tomorrow.

**Comment by AccidentallyOnPurpose** [comment]
you and me both!
