### ISSUE TITLE
Optimal loss for a custom model

### ISSUE THREAD

**Issue by MrReplikant** [cloveranon/Clover-Edition#140]
So I'm working on an experimental model of my own, meant to be considerably more lightweight. Preliminary testing has shown that it at LEAST has the "mental capacity" to be functional. Right now it's at an average loss of 1.20 when training under NSheppard's fork of GPT-2. I read a few articles saying that I should train it until near zero, but I have to wonder if in this use case that would be overfitting?I concede my understanding may be flawed. If anyone here has an idea of about where to stop the training, I'd greatly appreciate it!

**Comment by fen0s** [comment]
"near zero" is usually overfit, yeah.
1.20 seems not bad already, i'd train it to about ~0.7-0.9. remember than AID model is hugely overfit yet gave out good results? but spew out men in black constantly. overfitted model is usually good on text generation quality, but not very flexible, so it's double-edged sword.  i'd say that there's no general "good" loss and you should judge when stop by samples and looking if they repeat one-in-one some chunks from original dataset.

**Comment by MrReplikant** [comment]
Thank you! It's now at 1.00, so it's going well. I'm trait over CPU cause broke and me and Google just don't Colab (get it?) So it's definitely been no small amount of time invested. This'll definitely save me some development time. Thanks again!

**Comment by Skhmt** [comment]
Solved?

**Comment by MrReplikant** [comment]
Yes, sorry about that
