### ISSUE TITLE
GPT-Neo?

### ISSUE THREAD

**Issue by Skhmt** [cloveranon/Clover-Edition#143]
How can we get Clover Edition to run a GPT-Neo model, like from https://github.com/finetuneanon/gpt-neo_dungeon or https://huggingface.co/EleutherAI ?

Running the notebook from gpt-neo_dungeon takes less than 8 GB of VRAM, so it's physically possible for most users with a gaming GPU to do so at home and offline, but the user experience with Clover Edition is much better than a jupyter notebook.

**Comment by MikkoMMM** [comment]
This was talked about by @Meanmelter [here](https://github.com/cloveranon/Clover-Edition/pull/136#issuecomment-829714645). From that it seems it will require some changes.

**Comment by Meanmelter** [comment]
Support is being added here; In-fact I think we should implement some kind of toggle feature perhaps? #147
