### ISSUE TITLE
Loading prompts from pastebin gives an error 403

### ISSUE THREAD

**Issue by Skhmt** [cloveranon/Clover-Edition#146]
It gives an error 403 correctly, but that means it'll always show the error because the paste is private or pending moderation.

You can find a backup of the pastebin here to maybe make a new one:
https://web.archive.org/web/20200530194515/https://pastebin.com/raw/KD4yN2Gc

**Comment by MikkoMMM** [comment]
Maybe somebody has flagged it and it will reopen after a while? It seems weird to think the uploader would make the paste private after all this time.

**Comment by SammCheese** [comment]
I believe it was Privated because its detected as harmful content.
I tried reuploading it but it only gave me the option to post Private due to that

**Comment by MikkoMMM** [comment]
I've been reading about other pastes having these issues as well. Some of them have been restored as public (I don't know if they had to ask admins for that), other pastes not. It looks like they have some automated system detecting NSFW stuff.

**Comment by SammCheese** [comment]
Uploaded newly. replace the link on Line 22 in the pastebin.py file with this `https://ghostbin.co/paste/d4uh/raw`

**Comment by SammCheese** [comment]
Think this Issue can be closed now
