### ISSUE TITLE
Default option number

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#149]
@Meanmelter, I somehow didn't internalize that this would happen, but [this tiny change here](https://github.com/cloveranon/Clover-Edition/commit/0f3a392b271d34b4b862405393f8cc777878b8c5#diff-09d0cbaf891d623ac245ccf84485a687b554217349ca55557c60b33234b969ae) made it so that instead of queries like
`Enter a number from above (default 0):`

we now have
`Enter a number from above (default {default}):`

Was this change necessary for whatever reason?

**Comment by Meanmelter** [comment]
Weird, I thought the f was just a typo. I should have inspected input_line more.
