### ISSUE TITLE
Cannot load neo models

### ISSUE THREAD

**Issue by MNarath1** [cloveranon/Clover-Edition#158]
So i have almost no info on this but if you use the install script and afterwards use the play script at least for me it will not load the neo model into the gpu instead it will load around 5 GB into ram and then just stop there even after 10 minutes of waiting nothing happened installing manually works normally and it also loads the neo model into the gpu this only seems to happen if you install it with the script. Couriously the normal v5 model loads into the gpu just fine. To be more exactly it gets stuck at 5517.3 RAM and there is CPU activity but except for  that nothing else happens the whole time the GPU VRAM does not change at all.

**Comment by MNarath1** [comment]
Ok i tried to delete the venv folder and afterwards executed the install script again now it works i am confused possible that it somehow installed something wrong when the script got interrupted the first time but i can't really confirm nor deny it

**Comment by AtaIanta** [comment]
>  it will load around 5 GB into ram and then just stop there even after 10 minutes of waiting nothing happened
So it's not normal behavior? I have the same experience, but I am using vanilla GPT-Neo 2.7B. The RAM jump to 10GB, for 15 minutes nothing and then suddenly after 15 minutes it load everything and then compress to GPU (the same goes for force-CPU).

**Comment by MikkoMMM** [comment]
I'm going to ping @finetuneanon as well since this is sounding like what we talked about that they've made it so that GPT-Neo loads into system memory by default after a recent commit,

**Comment by Skhmt** [comment]
Under both models my RAM spikes just before loading to the GPU, but it settles down almost immediately, not after 15 minutes.

**Comment by finetuneanon** [comment]
> I'm going to ping @finetuneanon as well since this is sounding like what we talked about that they've made it so that GPT-Neo loads into system memory by default after a recent push, and I don't know how that link there works (whether it is some kind of an archived thing or packages the current head).

Originally my transformers fork always tried to instantiate the model directly on GPU, because otherwise Colab would run out of system memory. Recently I got a report that this prevents the models from loading at all for people without enough VRAM, so I changed it to load to system memory before outside of Colab.

However, since this seemed to cause performance issues for some people, I have now changed it again, so it will default to loading on GPU if there are more than 8GB of VRAM on the device. That was twelve hours ago, which explains why reinstalling it eleven hours ago fixed the issue. Apologies for the confusion it may have caused.

**Comment by MNarath1** [comment]
Well like i said i was able to fix it after deleting the folder and afterwards rerunning the install script but its possible that its connects to some other issues

**Comment by MikkoMMM** [comment]
For people having this problem, fxing this may require uninstalling transformers and then reinstalling:

```
pip uninstall transformers
pip install https://github.com/finetuneanon/transformers/archive/refs/heads/gpt-neo-dungeon-localattention1.zip
```
(May need to prepend "python -m" or "py -m" on Windows to that)

Uninstalling first was needed at least in one prior problem. Probably some cache thing. I think we should leave this issue open for a bit so if somebody has the same problem, they'll find it more easily.

**Comment by cloveranon** [comment]
It takes my PC 12.6 minutes to load the original model_v5 into the GPU. Neo would presumably take longer, haven't tested it yet. The problem seems to be running out of available RAM and hitting the swap. Converting the model to 16 bit fixes the issue, it only takes 33 seconds to load it. I added this as a note to the readme.

**Comment by Skhmt** [comment]
How much RAM do you have, how much was it using?

**Comment by Skhmt** [comment]
I wonder if `pip --no-cache-dir install https://github.com/finetuneanon/transformers/archive/refs/heads/gpt-neo-dungeon-localattention1.zip` would work best

**Comment by MikkoMMM** [comment]
Since we have been bumping into cache issues twice now at least, it may be worth considering having that flag set in the instructions and install scripts regarding transformers.

**Comment by Skhmt** [comment]
Doing some testing then I'll push something shortly

**Comment by Skhmt** [comment]
It's been a few days since --no-cache-dir has been added, closing issue.

**Comment by finetuneanon** [comment]
> It takes my PC 12.6 minutes to load the original model_v5 into the GPU. Neo would presumably take longer, haven't tested it yet. The problem seems to be running out of available RAM and hitting the swap. Converting the model to 16 bit fixes the issue, it only takes 33 seconds to load it. I added this as a note to the readme.

Monolithic torch pickles are a bad format for storing weights of huge models in my opinion. You need twice the RAM you need for using the model while loading it. Once a 6.7B model arrives, it'll definitely start making sense to prepare and distribute "sliced" models that have each layer's weights in a separate file. It would require some additional code for loading the weights and of course prepared model files. You can see the approach in the last cells of this notebook:

https://github.com/finetuneanon/misc/blob/main/SizeTest.ipynb

**Comment by Skhmt** [comment]
Is there a 6.7B coming? Will that be GPT-NeoX?

**Comment by finetuneanon** [comment]
There is currently a jax based model of that size being trained, but no timeline for release of course.
