### ISSUE TITLE
Cleaning up branches

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#166]
We have a whole lot of branches that haven't been touched in a long time. It could be an idea to do some spring cleaning and remove most of them. For my part, there's the prompt-toolkit branch which was merged at some point if I remember correctly but never deleted.

**Comment by Skhmt** [comment]
I agree, branches that have gone more than a year without a commit should be removed.

**Comment by cloveranon** [comment]
I have no memory of what is in most of these branches.

**Comment by Skhmt** [comment]
killed the stale branches, they've all gone 12-17 months without commit, many were already merged anyway
