### ISSUE TITLE
[SUGGESTION] gamename in download_model.sh

### ISSUE THREAD

**Issue by machiavel23** [cloveranon/Clover-Edition#17]
I was looking at your download_model.sh, and noticed this :

if [[ -d "${MODELS_DIRECTORY}/${MODEL_VERSION}" ]]; then
	ANSWER="n"
	echo "AIDungeon2 Model appears to be downloaded."
	echo "Would you like to redownload?"
	echo "WARNING: This will remove the current model![y/N]"

Maybe you should change "AIDungeon2" to "Clover-Edition"? Just a suggestion!

**Comment by AtaIanta** [comment]
changed
