### ISSUE TITLE
Syntax error install.sh

### ISSUE THREAD

**Issue by jONALDjONALD** [cloveranon/Clover-Edition#177]
it might be "werks on my machine" kind of thing but I keep getting a error running "sh install.sh"
_install.sh: 5: install.sh: Syntax error: "(" unexpected_
It could be a LMDE thing or im just unlucky to have a stupid computer.

**Comment by finetuneanon** [comment]
Try bash instead of sh.

**Comment by jONALDjONALD** [comment]
that didn't seem to work either.
_fatal: not a git repository (or any of the parent directories): .git_

**Comment by renatbabacaev** [comment]
This method worked for me:

You will need `bash` to launch `install.sh` because it uses it.
Install `bash` if you don't have it. Then run `chmod u+x install.sh` (solution from [here](https://stackoverflow.com/questions/36323771/syntax-error-do-unexpected-expecting)) and launch it with `sudo bash install.sh`.

**Comment by jONALDjONALD** [comment]
> This method worked for me:
> 
> You will need `bash` to launch `install.sh` because it uses it.
> Install `bash` if you don't have it. Then run `chmod u+x install.sh` (solution from [here](https://stackoverflow.com/questions/36323771/syntax-error-do-unexpected-expecting)) and launch it with `sudo bash install.sh`.
> 
> Also, make sure that the end-of-line is set to `LF` for this file.

this didn't even work as well, it just gave me the same error from the "bash" command

**Comment by renatbabacaev** [comment]
> ...it just gave me the same error from the "bash" command

What's the error from the bash command?

**Comment by jONALDjONALD** [comment]
the exact same actually
_fatal: not a git repository (or any of the parent directories): .git_

**Comment by Skhmt** [comment]
You can always try the os-agnostic install (install python, install requirements.txt, install cuda or cpu-requirements.txt, download a model).

**Comment by finetuneanon** [comment]
Change this line:

```
commit_hash=$(git log --pretty=format:'%h' -n 1)
```

to

```
commit_hash=unknown
```

**Comment by MikkoMMM** [comment]
Hmm, I'm not that familiar with this but from that fix suggestion, it looks to me like the install.sh kind of expects that you downloaded the repository via git clone. What about the people who downloaded the ZIP package? That possibility should be taken into account as well somehow.

**Comment by jONALDjONALD** [comment]
> Change this line:
> 
> ```
> commit_hash=$(git log --pretty=format:'%h' -n 1)
> ```
> 
> to
> 
> ```
> commit_hash=unknown
> ```

hey that worked! thank you so much! for some reason the CUDA thing didn't install but the program works perfectly now!
