### ISSUE TITLE
Linux Privacy

### ISSUE THREAD

**Issue by TheYellowArchitect** [cloveranon/Clover-Edition#184]
Short Question: If I install this on Linux, are there any issues with Privacy?
Asking because on one of the packages it installs (on windows at least), I saw one related with Intel, and I do not think Intel cares about privacy at all

**Comment by MikkoMMM** [comment]
Which package are you talking about? Was this through the install.bat?

**Comment by AIDungeonWiXAnon** [comment]
I assume this is about the intel-openmp package that's installed for PyTorch - it just provides an API that's used for multithreading, as I understand. The devs go into more depth about this [here](https://github.com/horovod/horovod/issues/389).

**Comment by TheYellowArchitect** [comment]
That is definitely the package, I remember it had 'open' something, but wasn't certain
I sadly don't know anything about the API, and don't trust Intel with anything, but anyway I am closing the issue as I (likely) got this working on Windows :sweat_smile:
