### ISSUE TITLE
Sugestions error

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#19]
```
Traceback (most recent call last):
  File "play.py", line 460, in <module>
    play(generator)
  File "play.py", line 250, in play
    if suggested_action[0] not in ["'", '"']:
IndexError: string index out of range
```
I changed in config `action-min-length` to have more complex suggestion because sometimes it given me "yes" or short verbs but i don't think thats the cause of problem.

edit: it happened once one hour ago and I am not able to reproduce this

**Comment by AtaIanta** [comment]
ok got it again after 40~ actions

**Comment by cloveranon** [comment]
Presmably related to https://github.com/cloveranon/Clover-Edition/commit/c1c30246eca08fc8a70b6444c8eca2cc5523b32f

**Comment by cloveranon** [comment]
I think that fixed it check if you are on the latest version.

**Comment by AtaIanta** [comment]
I'll reopen if I would see error again

**Comment by AtaIanta** [comment]
now it looks like AI eats one of the suggestion without an error (the origin of problem propably is the same) but it's bearable
![image](https://user-images.githubusercontent.com/42716753/71469188-9ed62c00-27c8-11ea-81b9-d23c48943886.png)
