### ISSUE TITLE
Discussion action generation

### ISSUE THREAD

**Issue by AccidentallyOnPurpose** [cloveranon/Clover-Edition#2]
I noticed a comment
> Can we just use a for loop to generate actions

Yeah good idea, then we could display each one to the user, keeping responsivness.

> We still need to delete suggestions and user input

Any ideas on how to do that? I was deleting N lines, but with text wrapping that doesn't work. We could restrict the actions to 80 or line-width charectors, then delete lines?

Is there a way to delete terminal outputs untill you get to a certain charector, e.g. Suggested actions?

**Comment by AccidentallyOnPurpose** [comment]
A few comment on changes I made
- I added ability to enter a number to choose an action, feel free to remove if you didn't want it
- "Save half memory in readme". Turns out using half only save ~20%, so I updated the readme. For me it goes from 11G -> 8G
- I'm also going to change the magnet to a torrent file since anons don't have t owait for metadata to populate

**Comment by AccidentallyOnPurpose** [comment]
Oh never mind, I counted wrapped lines

**Comment by cloveranon** [comment]
We can disable text wrapping, colPrint already has an option for it. I need to check if Windows and colab support the line movement codes.

**Comment by AccidentallyOnPurpose** [comment]
Oh nice. But it's alright I managed to make it work with text wrapping
