### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by ieXPXP** [cloveranon/Clover-Edition#205]
I keep getting error code 502, any idea as how to fix it?
![Screenshot (59)](https://user-images.githubusercontent.com/86382216/123364472-74426c00-d542-11eb-9d8e-7375f4a0fc09.png)

**Comment by SammCheese** [comment]
Hmm, i feel like Custom Prompts got yeeted, ill look into that

**Comment by SammCheese** [comment]
Fixed, just update and it should work again
