### ISSUE TITLE
Converting tensorflow models made by anons

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#21]
I try to use convert tool and I am getting an error, this is my command as `export` and Windows' `set` is not working, also breking command with \ gives another error:
```
python convert_gpt2_model.py --gpt2_checkpoint_path ../generator/gpt2/models/model_v5 --pytorch_dump_folder_path ../generator/gpt2/models/model_v5_pytorch --gpt2_config_file ./aidungeonv2_model_v5_config.json
```
the result is
![image](https://user-images.githubusercontent.com/42716753/71482197-9e0dbc00-2801-11ea-8193-756aa9c14b30.png)
I am trying to convert smut model from https://mega.nz/#F!51ED1CSA!YbifAmboqSLCrr3Y78axqw!kxFVxaRZ

**Comment by AtaIanta** [comment]
ok I am dumb you need to use .json from model not one provided with converter

**Comment by AtaIanta** [comment]
I converter new model from anon http://sys.4channel.org/derefer?url=https%3A%2F%2Fmega.nz%2F%23!11x23IQY!x3FAeke6XkuBfUdQu6aC4eqzkK8NKu5CEPdTon1oaKw
and converted. Percentage of VRAM usage is insane
![image](https://user-images.githubusercontent.com/42716753/71483361-cbf5ff00-2807-11ea-947f-3801a385a0b5.png)

But the responses aren't as good as original. 
![Uploading image.png…]()

So I have a question, is converting models not possible with current version of converter?

**Comment by AtaIanta** [comment]
Lowering temp and top-k seems to working but still sometimes bit too random
link to novelmodel if someone wants to test
https://mega.nz/#!5EYDzahB!GAYM4sPcpU9XvmKw5uIIkJvNLhcNMaE4j9WVDeNUoBA

**Comment by Meanmelter** [comment]
Hmm. That makes me wonder if models that are trained with more data, or longer, take up more VRAM.

**Comment by Meanmelter** [comment]
I would imagine a wider library of inputs = Better responses + More VRAM required.

**Comment by cloveranon** [comment]
There should be no noticeable difference with the downgrade to 16 bits. I created the [test-models.py](test-models.py) script to test the difference in output of running on 16 bit GPU vs 32 bit CPU. It was well within my expectations.

![2019-12-25-220314_790x684_scrot](https://user-images.githubusercontent.com/58804713/71493828-2d21d080-2810-11ea-9c30-2578ae543ebb.png)

**Comment by Meanmelter** [comment]
Yeah sounds good to me. That does make me curious if there's any ML that has 8-bit Floats, we could probably drop the usage even further this way. Might be time to pickup Python again hehe.
Would you expect that models that take more VRAM but use the same bits would perform better in general?

**Comment by cloveranon** [comment]
@Meanmelter Yes 8-bit integer math is supported for neural networks. It is not trivial to use. You may have to rescale the parameters to fit within the limited range. And it likely requires retraining in a special way to make the parameters "quantization aware" (I think they basically add random noise to the weights to simulate rounding errors.) I also think some of the accumulations are still done with floating point or larger integers to reduce rounding errors when summing lots of small numbers (although there are special algorithms for that I know of.)

All of that is way beyond my ability though.

I've never heard of 8 bit floats but I don't see why it couldn't be done.

There's also a special process called "distilation" that's supported by huggingface-transformers. They have a script to train a much smaller model to perfectly mimic the output of a larger model. And could theoretically reduce the memory usage by more than half.

**Comment by AtaIanta** [comment]
Nice green clover, this is custom or it should look like this by default? Cause now it shows white for me.

And one more question, should we add to the readme instructions for converting models? Some anons on /v/ want do it by themselves and it's not clear now how.

**Comment by cloveranon** [comment]
The clover logo abuses a lot of terminal features to look like that. It definitely won't work in the windows command prompt. Sadly most users will never see what it's supposed to look but that's ok.

I put some notes in the README. But even I'm not sure how to do it for some of the smaller models. I don't know where the [aidungeonv2_model_v5_config.json](pytorch-scripts/aidungeonv2_model_v5_config.json) file came from or where you would get one for other models.

**Comment by AtaIanta** [comment]
That config is from original model v5 for Nick I guess, cause using this with other models made by anons gives error mentioned in the first post. 

This is command which works for me

````
python convert_gpt2_model.py --gpt2_checkpoint_path ../generator/gpt2/models/model_v5 --pytorch_dump_folder_path ../models/dump/ --gpt2_config_file ../generator/gpt2/models/model_v5/config.json
````
with `../generator/gpt2/models/model_v5/`
being the path to model you want to convert and `config.json` being a file in that folder with some variables (can I call it variables?) necessary for convertion, `../models/dump/` is path you want to create converted model and that catalog must exist.

Then you must copy `vocab.json` from original model to new pytorch model as the script doesn't copy it.

**Comment by renekris** [comment]
Here are 4 Pytorch models, please tell me if there are any problems, I will try to fix any if they come up. Or if anyone wants I can convert more...

https://mega.nz/#F!4e5kRCIB!v7q0ItVjhhGcIqfZOZy9yA

**Comment by AtaIanta** [comment]
the Meganon model for sure once it gets online

**Comment by renekris** [comment]
I've made the model conversion quite simple, I have 2 folders, one for the dump and the other for the original model waiting to be converted. Just run a .bat and it converts without any problems. 
![image](https://user-images.githubusercontent.com/14850071/71527109-a0941280-28e2-11ea-931f-d0a95509a07b.png)

**Comment by AtaIanta** [comment]
But how the bat handles finding the *.json, you predertemine that or you are using some magic command?

**Comment by renekris** [comment]
That part I do manually, but it could be done automatically as the .json always comes with the GPT-2 model itself. I'm also using a different convert_gpt2_model.py that won't make a part file like the original does.

**Comment by AtaIanta** [comment]
But sometimes you have two *.json files which one of them would be vocal. However I'm interested in the change in code for not creating part file.

**Comment by renekris** [comment]
Can you tell me where the original convert_gpt2_model.py came from? Is it from the developers of Pytorch or by some anon?

**Comment by AtaIanta** [comment]
To be honest I don't know, I found instruction for conversion here https://github.com/AccidentallyOnPurpose/pytorch-AIDungeon/blob/develop/README.md so I guess @AccidentallyOnPurpose added this tool. In Clover pastebin however you have this link: https://github.com/huggingface/transformers/blob/17ea43cf985829634bd86b36b44e5410c6f83e36/docs/source/converting_tensorflow_models.rst 
Maybe AOP will answer your question

**Comment by renekris** [comment]
So after a while, I got the .bat improved on and I also configured the convert_gpt2_model.py.

![image](https://user-images.githubusercontent.com/14850071/71533458-6d14b080-2901-11ea-962e-2b092048af96.png)
From running the .bat

![image](https://user-images.githubusercontent.com/14850071/71533477-9af9f500-2901-11ea-9042-a7d8b4b6dad4.png)
The folder structure: dump(where the finalized files go after conversion); gpt2_model(where you put the files to be converted); merge_vocab(merge & vocab file that get transferred into the dump folder after conversion).

**Comment by AccidentallyOnPurpose** [comment]
I added the tensorflow conversion, jsut copyign transformers code.

Here are config.json file for 3 differen't sizes of GPT2, in case that's usefull https://github.com/huggingface/transformers/blob/17ea43cf98/transformers/configuration_gpt2.py#L29

I think pytorch doesn't support 8bit or lower yet.

**Comment by cloveranon** [comment]
The script appears to not require a config file. What does it do if you don't give it one?

**Comment by cloveranon** [comment]
With https://github.com/cloveranon/Clover-Edition/commit/74740894324656e81065bc018df7e3bf044b4575 I added an idiot proof tensorflow converter, [convert_gpt2_model.py](convert_gpt2_model.py). Tested so far only on the vanilla mormon model, let me know if it works on other models with no extra effort. See the updated README instructions also.

**Comment by renekris** [comment]
Sure, I can give it a try, I have all the models from the alternative models folder and some extra anyways

**Comment by AtaIanta** [comment]
how do you use the new script? Is it the same command as before? 
![image](https://user-images.githubusercontent.com/42716753/71539971-64919980-2944-11ea-946a-2b6ed1050de8.png)
gives me error if I use so

**Comment by renekris** [comment]
Just do `python convert_gpt2_model.py .\*path to checkpoint*`

**Comment by renekris** [comment]
Should get something like this 
![image](https://user-images.githubusercontent.com/14850071/71539999-4d0ade80-294d-11ea-804d-160bbc0a13ed.png)

**Comment by AtaIanta** [comment]
ok, it's working, thanks

**Comment by AtaIanta** [comment]
based cloveranon making models lightweight
![image](https://user-images.githubusercontent.com/42716753/71540013-18932480-2945-11ea-9198-834137a13d5f.png)

**Comment by AtaIanta** [comment]
And use even less memory, I wonder how mormon model eats VRAM after 16bit conversion
![image](https://user-images.githubusercontent.com/42716753/71540029-5d1ec000-2945-11ea-853a-26746f786f9d.png)

**Comment by renekris** [comment]
@cloveranon could it be possible to put the tf model into the models folder and when you python start.py it auto converts it and gives you the option to start it without ever dealing with conver_gpt2_model.py yourself?

**Comment by renekris** [comment]
Or another option is to convert each and every model manually and upload them all to mega, link it in README and have users pick and choose

**Comment by cloveranon** [comment]
Currently the game always converts to 16 bit for GPU and 32 bit for CPU (16 bit isn't supported on CPU by pytorch for some reason.) That is, regardless of the bits in the model. But a smaller model may use less memory while loading.

@renekris it's possible to do it automatically, I don't know how many people would need to do that.

I've asked for anons to convert models and share them so hopefully there will be links to other models soon.

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71541287-e5599100-2956-11ea-80fc-e672d12329c5.png)
![image](https://user-images.githubusercontent.com/42716753/71541291-f0acbc80-2956-11ea-9a1d-94af39856a94.png)
yeah, models use lower amout of RAM initializing, doesn't have much impact on VRAM. You need now 12GB instead of 16GB to initialize.

**Comment by AccidentallyOnPurpose** [comment]
The models that take up less VRAM may be based on a smaller version of GPT2?

We have been using XL, but [there is distill, regular, medium, and large](https://huggingface.co/transformers/pretrained_models.html). They use less resources to train and run but would have lower performance.

**Comment by AtaIanta** [comment]
Yes, the one using 3GB VRAM is 774M.
