### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Roshag** [cloveranon/Clover-Edition#23]
←[27m
Traceback (most recent call last):
  File "play.py", line 43, in <module>
    is_notebook = _is_notebook()
  File "play.py", line 34, in _is_notebook
    if 'IPKernelApp' not in get_ipython().config:  # pragma: no cover
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by cloveranon** [comment]
Fixed I hope: https://github.com/cloveranon/Clover-Edition/commit/8de1b230e3781c1ac4d78400b08d291bc72b4588

**Comment by Roshag** [comment]
Yep, it works. Thx
