### ISSUE TITLE
pick model version if there is more than one

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#25]
Nice feature to have if someone have more than one model (which isn't the common issue now). The script can check if there is more folder than one in `./models/` and ask which one do you want to run.

**Comment by renekris** [comment]
Would be great, perhaps list each model inside the model folder with file name & size if possible, no madder the name of the model folder itself.

**Comment by cloveranon** [comment]
Done: https://github.com/cloveranon/Clover-Edition/commit/74740894324656e81065bc018df7e3bf044b4575

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71539837-9570cf00-2942-11ea-96d6-5a2bfa61f182.png)

**Comment by cloveranon** [comment]
my bad. fixed https://github.com/cloveranon/Clover-Edition/commit/76c77d7c4d93e64a2c254d6cbadcabefafa18760

**Comment by AtaIanta** [comment]
yup, thanks

**Comment by cloveranon** [comment]
amazingly fast bug reporting thank you btw
