### ISSUE TITLE
Additional [[[[ in Colab + disability to remove lines

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#27]
![image](https://user-images.githubusercontent.com/42716753/71524688-e2b35900-28ce-11ea-895d-e90e8c0be4b7.png)

The colab version (which is now working, big thanks to the Kornilov1)  after input of the user adds [[[[[ to the console log and doesn't delete suggestions. This two issues are propably related to each other. One of the solution would be to disable removing lines in colab.

**Comment by AccidentallyOnPurpose** [comment]
I added this line, which might fix it? https://github.com/cloveranon/Clover-Edition/blob/master/play.py#L64

**Comment by AtaIanta** [comment]
Still gives [[[[[

**Comment by machiavel23** [comment]
I looked at @AccidentallyOnPurpose line edit. I think the problem might be deeper than that. the code uses only open [ but for python, a [ is usually the start point of an array, so it expects a ] at some point to close the array.

possible_values = [0, 1, 2]

that might be the problem.

**Comment by cloveranon** [comment]
Hopefully this fixes it https://github.com/cloveranon/Clover-Edition/commit/95c1190d387fa77473dfc3e29fc2e2bab0e000e0

>This function to detect colab use did not appear to work properly. I'm still not sure that it does https://github.com/cloveranon/Clover-Edition/commit/95c1190d387fa77473dfc3e29fc2e2bab0e000e0

**Comment by AtaIanta** [comment]
http://boards.4channel.org/vg/thread/276712139#p276854624
fixed now
