### ISSUE TITLE
Save/load option

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#28]
Now it's disabled, but many anons want it back.

**Comment by kik4444** [comment]
Why would this be disabled in the first place?

**Comment by cloveranon** [comment]
I intended to improve it and never did.

**Comment by Meanmelter** [comment]
Honestly just got used to editing my starting prompt to add on anything I wanted it to remember.

**Comment by devfag** [comment]
I'll get to work on an implementation today.

**Comment by AtaIanta** [comment]
How do you plan to make saving/loading mechanics? I thought about having loading at start as 3rd option after writing a custom prompt and saving by name, just type /save  and then game will ask what name the save should have

**Comment by devfag** [comment]
yeah that was my plan. no more of that dumb guid saving that changes every time you save. also, i'll have it remember the last savename you used in a game session, so if you hit enter without typing a name it'll overwrite that save

**Comment by devfag** [comment]
thinking about creating a `/summarize` command that would work as follows: it copies the story prompt into a new save, lets you write a story summary as the new starting context, and then uses the last result from the last game as the first result from this game. that way, it'll be easier for people to continue a story once it's gotten too big or the ai has gone loopy

**Comment by AtaIanta** [comment]
What if there is no save data and someone didn't type anything? Will save be just prompt name?

**Comment by devfag** [comment]
either that or it'll demand a valid name for the first time

**Comment by devfag** [comment]
prompt name would only work if you saved the prompt

**Comment by AtaIanta** [comment]
Summarizing is good option and very useful, especially when the whole context can change due to actions taken in game. 
I saw on mormon's discord an idea for the forced summarizing by the user after limit of prompts memorized by AI is achieved. So if the AI is only analizing 20 input + outputs it will force user to write summary after that amount of inputs + outputs. But in my opinion it's bad idea and writing summary by command is a lot better.

**Comment by devfag** [comment]
yeah everyone's mileage varies on when the ai starts to break down, so i don't think a strict limit is best

**Comment by AtaIanta** [comment]
And what about `/altergen` when you don't like the AI's output so you write the beginning of the output by yourself and AI tries to generate rest of it. For example
My input is: You read the title of the book
Output: You read the title of the book and you are amazed by it.
I don't like that output so I use /altergen command
Input: /altergen The book title is 
And then AI generate the rest of the output and the previous one is replaced by it.
New output: The book title is "Goetia", it have many images of demons.

**Comment by AtaIanta** [comment]
https://github.com/thadunge2/AIDungeon/issues/40
Reference

**Comment by devfag** [comment]
ohh i see. yeah, i'll take a look at that after i implement save/load and `/summarize`

**Comment by AtaIanta** [comment]
I forgot to ask about `/menu` and `/quit`. Will it ask if you want to save or will it save automatically to the recent save (this can overwrite the save someone want to have)

**Comment by devfag** [comment]
it'll ask if you want to save

**Comment by MikkoMMM** [comment]
For the Python Prompt Toolkit I have an idea for an alternative to /altergen which might make it even obsolete. In the multiline editor (during a /alter or /prompt or what have you), the user could press Alt+G and then the AI would generate new output in that exact spot. What makes me think that this is doable is that I heard talk of some kind of inserting an AI response midway a prompt for the Storybro fork, which they call the "official community version". By the way, I might switch to primarily developing that at some point since they might just be able to keep their promises about it quickly catching up to the other forks.

**Comment by AtaIanta** [comment]
So basically `/retry`?

**Comment by devfag** [comment]
https://github.com/cloveranon/Clover-Edition/pull/61 is the PR for saving/loading. Please have a look at if if you want.

**Comment by devfag** [comment]
https://github.com/cloveranon/Clover-Edition/pull/61 now merged; closing.
