### ISSUE TITLE
Error when no connection to pastebin

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#33]
I was helping some dude from Turkey and they have blocked pastebin in their county, kek. 
When he runned play.py it gives error:
![unknown-24](https://user-images.githubusercontent.com/42716753/71544587-b1e02c00-2981-11ea-8abb-e83e377b90f8.png)
It will be the same problem for someone playing offline. Not big issue though.

**Comment by cloveranon** [comment]
It's supposed to have the pastebin in a try block. It looks like the error is in the code that tries to log the error.

**Comment by cloveranon** [comment]
https://github.com/cloveranon/Clover-Edition/commit/bb49961703a0c0d7242814cceccc57b1cbfe34ee

Should work now.
