### ISSUE TITLE
Syntax error in play.py

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#34]
![hrtahtaeva](https://user-images.githubusercontent.com/42716753/71545989-3c308c00-2992-11ea-8ebc-b4a5f92ecf10.png)
I don't see where is the error, someone got this running clover on pc

**Comment by AtaIanta** [comment]
Person didn't used python before play.py

**Comment by cloveranon** [comment]
The other 52 lines are valid dos?

**Comment by AtaIanta** [comment]
I don't have idea, I was surprised too
