### ISSUE TITLE
Add Current Value Next to Default for Anons

### ISSUE THREAD

**Issue by renekris** [cloveranon/Clover-Edition#35]
Have a "Current value" as an addition to see the current value of the setting.
![image](https://user-images.githubusercontent.com/14850071/71547944-680e3a80-29af-11ea-8c9b-2f4bb6fb9a59.png)

**Comment by renekris** [comment]
Or rather make it show the current value next to the setting and have the default set as the recommended value

**Comment by AtaIanta** [comment]
Do to so it's necessary to change /interface/ folder (or just this file dor settings) to some .py file. If i wasn't so lazy to learn python and finally help something in this fork besides making issues I would do it myself. (Maybe in the end of a day I will learn)

**Comment by AtaIanta** [comment]
I coded something but I don't like the way of putting many print's and there is no way to colorize it with current colPrint function, i don't like putting this in play.py either, It would be nice to have one file just to edit all interface texts
![image](https://user-images.githubusercontent.com/42716753/71557435-752a3880-2a46-11ea-93ac-354304e84651.png)

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71558127-d3a7e480-2a4f-11ea-81ed-2a67b4517f7b.png)
It works

**Comment by AtaIanta** [comment]
Implemented
