### ISSUE TITLE
AI ignoring user inputs

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#36]
Common issue, game tends to ignore inputs and just simply continue with his previous output, especially in dialogues. 

![Screenshot_20191229-072332_Discord](https://user-images.githubusercontent.com/42716753/71553249-88201700-2a0c-11ea-811d-f37beb125510.jpg)

![Screenshot_20191229-073007_Discord](https://user-images.githubusercontent.com/42716753/71553272-14323e80-2a0d-11ea-9ee6-c4efcef64135.jpg)

![Screenshot_20191229-073857_Discord](https://user-images.githubusercontent.com/42716753/71553328-4f813d00-2a0e-11ea-9247-e5964d995aa2.jpg)

Maybe there can be way to give users' inputs some sort of priority like previous actions being a context and input being prompt (which is the case in generating story). If I am reading logs correctly now AI gets full prompt as one big chunk of text with input being glued at the end. 

And that `> You` is often appearing even in middle of the output which really ruin the immersion
![Screenshot_20191229-073709_Discord](https://user-images.githubusercontent.com/42716753/71553321-252f7f80-2a0e-11ea-9b87-8bebf6f4ba44.jpg)

**Comment by cloveranon** [comment]
I think this is mostly a model issue that is hard to fix without retraining. It's possible it's exacerbated by the repetition penalty somehow, or some other setting. I'm looking at the generator code now and it looks like there may be some things that could be improved.

**Comment by cloveranon** [comment]
This branch is experimenting with some things related to generator and settings. https://github.com/cloveranon/Clover-Edition/tree/experimental

**Comment by AtaIanta** [comment]
why are suggestions not generating
![image](https://user-images.githubusercontent.com/42716753/71556517-ec0d0480-2a39-11ea-9338-b0c536bf6e26.png)

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71556568-bae10400-2a3a-11ea-9ef7-cecd3515c19d.png)
debug

**Comment by AtaIanta** [comment]
and now it's looping too hard

**Comment by Meanmelter** [comment]
My first story would just generate one sentence and repeat it.
Second story coming along well though, asides from general AI mishaps. Dome seem to repeat here though a bit.
![image](https://user-images.githubusercontent.com/17638040/71560780-165fc180-2a3c-11ea-91f1-4bc7ab1a93e8.png)

**Comment by AtaIanta** [comment]
Have you changed to have space after `>`?
BTW. I have suggestions now somehow but I didn't download anything, strange.

**Comment by Meanmelter** [comment]
No, it adds the space when you use the  _print_ command.

**Comment by AtaIanta** [comment]
Hmm, it's the error on log or the code remove latest prompts instead of the earlier one
![image](https://user-images.githubusercontent.com/42716753/71561261-8d18b100-2a74-11ea-8b2a-d4463e42483c.png)

**Comment by cloveranon** [comment]
An anon suggested some kind of automatic test for generation quality. I'm thinking bleu scores of known good outputs might work. Or manually rating a bunch of outputs generated with different settings. Any ideas?

**Comment by cloveranon** [comment]
White space has to appear after the '>' the way the tokenizer works. "You" and " You" are encoded completely differently. But I didn't change it recently.

**Comment by Meanmelter** [comment]
> 
> 
> An anon suggested some kind of automatic test for generation quality. I'm thinking bleu scores of known good outputs might work. Or manually rating a bunch of outputs generated with different settings. Any ideas?

That starts crossing into territory where I don't feel I can make a good call on things.
I would suggest the latter. You could make a fork that does this, and task someone with doing 100 different responses on like 10 different initial prompts. We could use the existing suggestion feature for this. 1-5 are different generated outputs, and you can have it ask which outputs make the most sense contextually. At the end it can compile the results per prompt and hopefully we will see some pattern.
If I had to guess, each setting is going to have a "Sweet-spot" where certain prompts work amazingly for it's setting and other's do not.

**Comment by Meanmelter** [comment]
After trying different configurations from https://github.com/cloveranon/Clover-Edition/tree/experimental for most of the day. I think the initial top-p of 0.25 is too low. Everything eventually repeats unless you set it higher, like to 25 or something. I still got the occasional AI suddenly changing my input, or making a sudden change in pace.

**Comment by cloveranon** [comment]
Thank you for your feedback. I'll raise it next commit.

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71578934-761ca200-2afa-11ea-972f-9f85b057f0e8.png)
on new experimental branch, the stories seems to be more coherent, this is my third round and the two previous ones looked similar

**Comment by cloveranon** [comment]
Thanks for your testing. I'm going to try some massive changes that might fix this in the next commit, stay tuned.

**Comment by AtaIanta** [comment]
Have you seen post about debug log? Cause after some longer playing in the game I felt like AI is only working on the information it have at the begging plus an user input and completly ignored prompts. I haven't have debug to check if that was the case.

**Comment by cloveranon** [comment]
I somehow missed that. I know AOP added some code to randomly select from the past history instead of just cutting off everything beyond a certain point.

**Comment by AtaIanta** [comment]
Literally why, wouldn't this fuck up linearity of the story? Maybe this would be good for coomers but for general use I don't see an use for something like this. I thought that an AI is using context and the latest 20 prompts (which I think that number should be adjustable in config.ini).

**Comment by Meanmelter** [comment]
Hmm so it picks 5 random past history entries... That kind of makes sense why context gets screwy after 10-ish prompts in... Is last 20 prompts highest we can go? What if we made it like 50 for a good laugh? Might be a good improvement

**Comment by AtaIanta** [comment]
We can even give 100, I think `self.memory = 20` in `story/story_manager.py` is setting for that

**Comment by Meanmelter** [comment]
Might be worth tracing where that code was committed, commenting out, and editing self.memory. I can do some research and testing later today.

**Comment by cloveranon** [comment]
Did text passing issue occur near the suggested actions? Because the suggested actions do more history randomization but won't affect the main game.

**Comment by Meanmelter** [comment]
Looks like flip happened at db0cdaed169aaef1b41771d7fac2e012c4babd47 with main branch. I believe actual change happened in other branch before it was merged.
I pulled `class AIPlayer` from the previous repository from master from 8632668bcad5a7f7c6540f09fe89c2be206d5e42. This is the only change I have made.
I have ran two stories up to ~20 prompts, and in my opinion it was a pretty nice improvement context-wise. People I killed in the first few prompts didn't suddenly just show up continuing off of the same prompt they got introduced with, and overall had somewhat better replies. Only real downside I had was a few times the AI would output nothing, had to revert 4-ish times to get it to not be stuck.
I think this may need further testing though; I still have the same config from the experimental branch and have not adjusted the `self.memory` at all.

**Comment by cloveranon** [comment]
AI player is just a function that generates suggested actions. It *shouldn't* interfere at all with the story generations. If you disable suggestions that code should never run anyway.

**Comment by Meanmelter** [comment]
Damn, back to the drawing board. Must have gotten lucky with AI generation then. I thought I was looking at the right story manager when I was deciphering play()

**Comment by cloveranon** [comment]
All the memory issues should be fixed in the new update on the experimental branch. It's probably super buggy in other ways though.

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71613908-1c26e580-2ba9-11ea-9a7d-15f1db2f067c.png)
![image](https://user-images.githubusercontent.com/42716753/71613999-b25b0b80-2ba9-11ea-96cb-c0abbd384895.png)

What is wrong with powershell and why it doesn't display suggestions

**Comment by AtaIanta** [comment]
too much \n
![image](https://user-images.githubusercontent.com/42716753/71614347-63ae7100-2bab-11ea-8732-55d96690b7f9.png)

**Comment by cloveranon** [comment]
I get the same result on the Dave prompt every time. Maybe temperature just too low for interesting battles.

I'm aware of the newline issue, probably best to disable actions for now until I can properly fix it.

**Comment by AtaIanta** [comment]
At least it's not ignoring user inputs anymore
![image](https://user-images.githubusercontent.com/42716753/71614500-52199900-2bac-11ea-94c9-37658263d0d4.png)

**Comment by cloveranon** [comment]
Also apparently changing most settings in game is completely placebo, they are all set when the game loads. I don't know how long it's been like that but it is my top priority next.

**Comment by cloveranon** [comment]
I believe settings now actually work when changed in game.

**Comment by Meanmelter** [comment]
I was able to change the settings and they worked for me. I tested by starting with current defaults, and then setting temp to 0 half-way through story. Next prompt was always the same prompt. Was able to change other settings too such as text-wrap-width.
