### ISSUE TITLE
password letters in colab

### ISSUE THREAD

**Issue by cloveranon** [cloveranon/Clover-Edition#39]
![img](https://i.4cdn.org/vg/1577753809785.png)

Only one users has reported this so far and it may have nothing to do with us. Still it makes me wonder. We added an optional import of readline to fix user input on some linux machines. Could using readline in colab possibly cause this?

**Comment by cloveranon** [comment]
Another anon has just reported this occurs on thadunge which would imply it can't be our fault.

**Comment by cloveranon** [comment]
Apparently thadunge also added readline recently so this may still be on our end.

**Comment by cloveranon** [comment]
Readline is now won't import if on colab

**Comment by machiavel23** [comment]
I think it might be browser related. maybe some piece of code changes the class of the textfield, making the browser interpreting it as a password field?

**Comment by machiavel23** [comment]
http://i.4cdn.org/vg/1577828741305.jpg

**Comment by Muskelmagier** [comment]
If you look at it every input field is now a  password type, but the readable ones have a extra line

**Comment by cloveranon** [comment]
Hopefully this fixes ithttps://github.com/cloveranon/Clover-Edition/commit/95c1190d387fa77473dfc3e29fc2e2bab0e000e0

>This function to detect colab use did not appear to work properly. I'm still not sure that it does https://github.com/cloveranon/Clover-Edition/commit/95c1190d387fa77473dfc3e29fc2e2bab0e000e0

**Comment by machiavel23** [comment]
https://github.com/thadunge2/AIDungeon/tree/41e966879dc9fce6bcdb1591c7389254e76cf974
https://github.com/thadunge2/AIDungeon/commit/41e966879dc9fce6bcdb1591c7389254e76cf974
that's the very moment the glitch showed up in thadunge repo

**Comment by cloveranon** [comment]
I figured it was readline.

**Comment by machiavel23** [comment]
![image](https://user-images.githubusercontent.com/30846033/71637794-9a3cc800-2c4d-11ea-8e55-92caf8e628d5.png)


does it help?

**Comment by cloveranon** [comment]
Oh that's just perfect

**Comment by machiavel23** [comment]
found on stackoverflow. best source of tips and tricks to deal with colab

**Comment by cloveranon** [comment]
Implemented: https://github.com/cloveranon/Clover-Edition/commit/31ebad205ef741c140d8627723d203a3348a7b4f

**Comment by cloveranon** [comment]
OK readline should now and truly be disabled for colab users. If this doesn't fix it then it isn't readline. I'm worried that may be the case.

**Comment by cloveranon** [comment]
The bug is still present. I have no idea what to do now.

**Comment by cloveranon** [comment]
Ok I overlooked someone added readline to utils.py as well and all my checks were pointless. Fixed https://github.com/cloveranon/Clover-Edition/commit/bc975d967c928fe0fa6f719f74efd6bdf4e600de

**Comment by machiavel23** [comment]
https://github.com/cloveranon/Clover-Edition/commit/bc975d967c928fe0fa6f719f74efd6bdf4e600de#commitcomment-36628099

**Comment by cloveranon** [comment]
Thank god.
