### ISSUE TITLE
Clover Edition Installers

### ISSUE THREAD

**Issue by AIDungeonpastes** [cloveranon/Clover-Edition#41]
I recently created an installer for this project: https://github.com/AIDungeonpastes/Clover-Edition-Installer/

**Comment by Meanmelter** [comment]
I will add to install video when I get a free moment, any chance you could put MD5, and  SHA-1 hashes for the download?

Is there a reason you went with CMD over Powershell?
You can use powershell to define a new protocol for magnets that should prompt them with a windows 10 pop-up to pick a program for it, that way it doesn't matter if they use qBittorrent or some other client.
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)?redirectedfrom=MSDN

**Comment by AtaIanta** [comment]
Does Powershell work on Windows 7?

**Comment by Meanmelter** [comment]
Actually it looks like there's already a magnet protocol in windows. Just doing `start "magnet:?xt=urn:btih:17dcfe3d12849db04a3f64070489e6ff5fc6f63f&dn=model_v5_pytorch&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.cyberia.is%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.moeking.me%3a6969%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2710%2fannounce&tr=udp%3a%2f%2ftracker3.itzmx.com%3a6961%2fannounce"`
Should be enough to start the download. we should be able to call this in cmd without quotes I think?

Also yes, Windows 7 SP1 has Powershell, but an older version.

**Comment by AIDungeonpastes** [comment]
No particular reason other than I'm not too experienced with Powershell, also the windows certutil command can be used to check hashes on files I believe, so that can be implemented, and I'll test to see if just starting the magnet will work as intended.

**Comment by cloveranon** [comment]
This is great.

**Comment by Meanmelter** [comment]
I just realized the magnet contains escape characters, you'll need to escape again with ^ and it should work.

**Comment by Meanmelter** [comment]
I just realized the magnet contains escape characters, you'll need to escape again with ^ and it should work.

**Comment by AIDungeonpastes** [comment]
Added hash checking, also instead of just starting the magnet link I may use aria2 to download it instead, just for max brainlet-proofing

**Comment by AIDungeonpastes** [comment]
I followed through with that and added aria2 to download the model, it seems like that's all that needs to be done for now.

**Comment by Meanmelter** [comment]
Updated video that also has instructions;
I would specify in readme which BAT file they need to run first, then run the other.

**Comment by AIDungeonpastes** [comment]
Clover_Installer.bat starts main.bat at the end of its script, but yeah I'll put it in there.

**Comment by cloveranon** [comment]
If you can make sure the torrent seeds and doesn't shut down immediately after downloading.

**Comment by cloveranon** [comment]
We also should make a new torrent with a 16 bit model so it will download faster

**Comment by AIDungeonpastes** [comment]
I'm pretty sure that it seeds, I just took the aria2 arguments from the download_model.sh file here, in the installer it looks like this.
`start /wait %aria% --max-connection-per-server 16 --split 64 --bt-max-peers 500 --seed-ratio=1.0 --seed-time=120 --summary-interval=15 --disable-ipv6 --check-integrity --stderr "https://raw.githubusercontent.com/cloveranon/Clover-Edition/master/model.torrent"`

**Comment by cloveranon** [comment]
That should have it seed for 120 minutes or until it reaches a ratio of 1.0. Which I think is fine. It will block the rest of your script from executing until it finishes though. It may be possible to make your script continue as soon as it's done downloading and let it seed in the background.

**Comment by AIDungeonpastes** [comment]
I could have it go something like
`--dir=Clover-Edition\models\ --out=pytorch-gpt2-xl-aid2-v5 --max-connection-per-server 16 --split 64 --bt-max-peers 500 --seed-ratio=1.0 --seed-time=120 --summary-interval=15 --disable-ipv6 --check-integrity --stderr "https://raw.githubusercontent.com/cloveranon/Clover-Edition/master/model.torrent"`
I don't know if --out works with directories though, I'll have to test it out.

**Comment by AIDungeonpastes** [comment]
OK it does actually work but I'll have to replace the .torrent link with the magnet for it to work properly.

**Comment by cloveranon** [comment]
Or download the torrent file locally and then use it.

**Comment by cloveranon** [comment]
Which it should already be downloaded after downloading the repo

**Comment by AIDungeonpastes** [comment]
Oh yeah, good point.

**Comment by AIDungeonpastes** [comment]
Also, does naming the folder pytorch-gpt2-xl-aid2-v5 matter much? since with aria2 you can't manipulate the outputted name of the file/folder in the case of torrent links.

**Comment by cloveranon** [comment]
The name does not matter anymore. Ideally it should have an informative name of what it is. But the code just grabs the first folder in `models`

**Comment by AtaIanta** [comment]
http://boards.4channel.org/vg/thread/276864298#p276871767
Some Anon made second installer

**Comment by AIDungeonpastes** [comment]
Nice, the more options the better.

**Comment by cloveranon** [comment]
https://github.com/AIDungeonWiXAnon/AID2-Installer-Project

**Comment by AIDungeonWiXAnon** [comment]
Making a pull request feels pompous, but is there any chance of getting https://github.com/AIDungeonWiXAnon/AID2-Installer-Project/releases added to the README.md alongside AIDungeonpaste's link for the installers? Should be stable enough to serve for general-purpose installs with v1.0

**Comment by cloveranon** [comment]
You should have the rights to edit it.

**Comment by devfag** [comment]
Nothing pompous about making a pr @AIDungeonWiXAnon, just good developer practice.

**Comment by AIDungeonWiXAnon** [comment]
Well, when it's to advertise your own work... Guess it just felt self-important, but I appreciate the assurances.
Anyway, I went ahead and made the commit to the README.md with 4b87e1c and added in a tidbit about Anaconda/Miniconda working, since it's what my installer uses to manage the python env and do most of the package installs.

**Comment by Meanmelter** [comment]
Now that installers have been documented on the Readme, should be able to close this.
If any big future updates come out we could make a new issue to have the other repos updated.

**Comment by SammCheese** [comment]
As Meanmelter said, Its been documented in the README.
If there are Big Updates, please open a new Issue 👍
