### ISSUE TITLE
MIGRATE

### ISSUE THREAD

**Issue by cloveranon** [cloveranon/Clover-Edition#48]
Kornilov1 has just been shoaed: https://github.com/Kornilov1/ They may come for us next. We should at least be prepared.

**Comment by cloveranon** [comment]
![kornilov1-shoaed](https://user-images.githubusercontent.com/58804713/71651431-58faf580-2ceb-11ea-8538-d65dc0aa4fda.png)

**Comment by AtaIanta** [comment]
I think (((they))) flagged him due to our statements against Mormon. I don't see any other reasons. Also I don't think we should have this issue here.

**Comment by AIDungeonpastes** [comment]
@cloveranon 
I think you should set up a mirror on either [GitGud](https://gitgud.io/) or [Codeberg](https://codeberg.org/)
GitGud is based on GitLab so the guide for that is https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html, and Codeberg is based on Gitea, which doesn't explicitly have a doc on repo mirroring but it lists it as one of its features here https://docs.gitea.io/

**Comment by Meanmelter** [comment]
We should setup a mirror, but I think trying to stay on Github would be best. Just follow TOS and there shouldn't be an issue.

**Comment by OpenCYOAI** [comment]
I agree with @Meanmelter

**Comment by OpenCYOAI** [comment]
It's mainly someone specifically hunting Kornilov1. The second account got flagged, and the third too. But for the third, I think it's because the nickname was just random numbers, Github's system might have think it's a bot.

**Comment by RyushoYosei** [comment]
Considering how the original person has acted, I wouldn't be supprised if he is harassing Kornilov1

**Comment by machiavel23** [comment]
https://github.com/VBPXKSMI/Open-CYOAI-Project/issues/144#issuecomment-572539262

**Comment by DonaldTsang** [comment]
Okay people, could we please sort out the license issues as per link from @machiavel23 and https://github.com/thadunge2/AIDungeon/issues/36

**Comment by Meanmelter** [comment]
I don't think this has been moved at all; As far as I know this is still the primary hub for Clover Edition - Close issue?

**Comment by SammCheese** [comment]
Clover seems to be Fine, no Mirror required.

Closing Issue.
