### ISSUE TITLE
/alter and /prompt not editing properly

### ISSUE THREAD

**Issue by AtaIanta** [cloveranon/Clover-Edition#50]
![image](https://user-images.githubusercontent.com/42716753/71655066-6b9a1c80-2d35-11ea-84e5-44384969edda.png)

when editing whole prompt script gives empty prompt afterwards

**Comment by AtaIanta** [comment]
editing by sentences works perfectly

**Comment by devfag** [comment]
been unable to recreate the bug on my end. was this done at the beginning of a game?

**Comment by AtaIanta** [comment]
It doesn't matter when I try to edit in powershell, when I try to edit whole prompt and write something, before saving looks fine but after it only spit out `>`. Can this be an issue if I don't write exactly the same amount of sentences as a prompt I want to edit? I don't know how editing only one sentence doesn't give the same error.

**Comment by devfag** [comment]
The section of code for editing the entire prompt is as follows:

```python
#(inside alterText)
        elif i == 3:
            colPrint("\n" + " ".join(sentences), colors['menu'])
            text = colInput("\nEnter the new altered prompt: ", colors['menu'])
            sentences = splitIntoSentences(text)
```

I don't see how this could be messing up unless the actual input is nothing. I'll add an empty string check to make sure you can't just wipe it.

**Comment by devfag** [comment]
Actually, can you try running the `/print` command after making an edit and see if the proper edit has been made?

**Comment by devfag** [comment]
Fixed in https://github.com/cloveranon/Clover-Edition/pull/54/commits/0bac4de43d162c9dd9ea5ee6957689a022797417, coming into main branch soon
