### ISSUE TITLE
List saved games when loading game

### ISSUE THREAD

**Issue by AIDungeonWiXAnon** [cloveranon/Clover-Edition#67]
> by the way, sorry for asking here but when you load a story in game, you don't get the list of the stories or win10 is shit and does'nt display them
>  ![image](https://user-images.githubusercontent.com/42716753/71762923-26f9b700-2ed6-11ea-916c-77d443e6b2c0.png)

_Originally posted by @AtaIanta in https://github.com/cloveranon/Clover-Edition/pull/64#issuecomment-570768199_

QOL more than anything, but felt like it was worth making as an enhancement.
Without looking at the implementation of load_story() I imagine this should be a reasonably simple affair of pulling the saves directory and spitting out the contents; I'll see about implementing this sometime later today unless someone else gets to it before I do.

**Comment by devfag** [comment]
I'll get to work on it soon. Was a silly oversight.

**Comment by devfag** [comment]
Implemented now in PR https://github.com/cloveranon/Clover-Edition/pull/64
