### ISSUE TITLE
Longer than two line long prompt files only get two first lines used

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#69]
An example for this would be cloveranon-prompts/kornilov.

I think the first line is interpreted as the context and the other one as the prompt. The rest are ignored. I tested that it's not an issue just with my Prompt Toolkit branch.

**Comment by devfag** [comment]
Yeah, the way the current prompt loading works is it takes the first line as the context and the second as the prompt. Not sure how we want to deal with this: have the context take all but the last line and have the prompt take the last line, or have the context take only the first line and have the prompt take the rest? We'll need to conform all the existing pastebin prompts to follow whatever standard we set.

**Comment by devfag** [comment]
Temporarily fixing this in PR#64 by making it so when a start has >2 lines, the first n-1 lines go to context and the last line goes to prompt

**Comment by AIDungeonWiXAnon** [comment]
Might be safest to only put the first sentence into context as a start, since the larger the context gets the slower the AI tends to be in generating outputs, at least from what people in the threads are saying and preliminary initial testing.

**Comment by cloveranon** [comment]
The way I had it it did file.readline() for the prompt and file.read() for the rest of the file for the context.

**Comment by AIDungeonWiXAnon** [comment]
I believe we have the same idea then; as far as I'm aware the meanings of context and prompt flip-flopped a bit ago (but to be specific, when I said context I meant the permanent memory, and by prompt I meant the 20-entry temporary memory.)
Thoughts @devfag?

Of course, without the pastebin anons ensuring their custom prompts are consistent we're bound to run into issues. Regardless though, keeping just the first line of a custom prompt in the permanent memory (context) of the AI feels like a safer standard to set from a performance standpoint to me.

**Comment by devfag** [comment]
Alright, I've made the change and will push it to master
