### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Nalewa** [cloveranon/Clover-Edition#7]
I was trying to run game but I always see this error:
`Initializing AI Engine! (This might take a few minutes)
12/24/2019 17:4747 - INFO - Using device=cuda, checkpoint=models\pytorch-gpt2-xl-aid2-v5, dtype=torch.float16
Traceback (most recent call last):
  File ".\play.py", line 321, in <module>
    play()
  File ".\play.py", line 113, in play
    generator = getGenerator()
  File ".\play.py", line 92, in getGenerator
    repetition_penalty=settings.getfloat('rep-pen')
  File "C:\AI\gpt2generator.py", line 134, in __init__
    self.model.to(self.device).to(self.dtype)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 426, in to
    return self._apply(convert)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 224, in _apply
    param_applied = fn(param)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 424, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 154.00 MiB (GPU 0; 8.00 GiB total capacity; 6.12 GiB already allocated; 128.97 MiB free; 69.20 MiB cached)`
I have installed python3.7.5, pytorch, etc. and the latest version of CUDA Toolkit and dumped cuDNN into CUDA folder, I am using Windows 10 but I doubt this is an issue here. 

When the game is starting cmd eats shitton of RAM, it's not touching VRAM. 
I have RTX 2070 so teoretically I should be able to play the game.

**Comment by AccidentallyOnPurpose** [comment]
Theoretically, you should be. When it starts up it uses 8GB, then once float16 is finished it uses 5-6GB. We could try and change the startup script to only use 5-6GB maybe.

So 1) Try closing other windows that use some, for example some browsers use gpu acceleration
2) We could try modifying the startup script and you could test it if keen

Image from Gabriram

![image](https://user-images.githubusercontent.com/4935931/71425593-b8775680-2696-11ea-8fef-992581bc791a.png)

**Comment by Nalewa** [comment]
after closing everything game still gives the same error, this is how the usage of RAM and VRAM looks (sorry for task manager graph but I don't have afterburner yet, the peaks in graphs happens at  the same time)

![RAM and VRAM usage](https://user-images.githubusercontent.com/42716753/71425784-53752e00-26a1-11ea-8987-ce642e4b4383.png)

so I think in the current state pytorch version doesn't support my GPU. CPU version works fine (excluding 60-90 seconds of waiting for response).

**Comment by Meanmelter** [comment]
Hm, I am having this now too. I have a similar setup: 16GB RAM, though I have a 2080 w/ 8GB VRAM. Are you using CUDA 10.2?
Torch CPU works fine for the most part, I noticed twice though on launch it doesn't seem to offload memory? Will sometimes stay at 15GB RAM used before loading a story. Close and re-open fixed it for me.

**Comment by cloveranon** [comment]
RTX 2070 is definitely supported by pytorch. I've had it crash a few times but it usually works on my 2070.

**Comment by Nalewa** [comment]
Yeah I have CUDA 10.2, earlier I had 10.1 to check if there would be a difference but got the same results. 

By supporting RTX 2070 I meant Clover supporting that gpu, but if it works for you @cloveranon then I don't know what can be a problem.

**Comment by Meanmelter** [comment]
I managed to get past the prompt screen by setting torch.float32 on GPU, though I wasn't able to get much further than that, loaded page to pick a prompt but OOM after that.
![float32](https://user-images.githubusercontent.com/17638040/71426640-95d74480-267a-11ea-99cc-26c30e7a423c.PNG)
Might be a way to alter it to work on the float16 but I am not sure. I am curious that it seems to load for some with a 2070 but not others.

**Comment by AccidentallyOnPurpose** [comment]
I pushed a new branch `develop2` that doesn't have that initial gpu ram peak. It goes directly to cuda float 16, feel free to try it. I think it may work on your gpu.

**Comment by Nalewa** [comment]
This is the output from `develop2`:
```
Traceback (most recent call last):
  File "play.py", line 14, in <module>
    from gpt2generator import GPT2Generator
  File "C:\AI\gpt2generator.py", line 198
    logger.debug("Text passing into model %s", self.tokenizer.decode(context_tokens, clean_up_tokenization_spaces=True, skip_special_tokens=True))
         ^
IndentationError: expected an indented block
```

**Comment by AccidentallyOnPurpose** [comment]
Ops fixed now

**Comment by AccidentallyOnPurpose** [comment]
Also could you please post a screenshot got dedicated gpu usage if you test it, like you did before. It's hard to plot that on linux.

**Comment by Nalewa** [comment]
Now the game is running smooth as fuck, good job!
This is what task manager gives me
![Untitled](https://user-images.githubusercontent.com/42716753/71427236-942b7200-26b6-11ea-899f-b038e458b351.png)

**Comment by AccidentallyOnPurpose** [comment]
Great! Thanks for testing the new branch too :p, I can merge this branch now!

**Comment by Meanmelter** [comment]
I can also confirm
![mem](https://user-images.githubusercontent.com/17638040/71427264-c0c69600-2684-11ea-86fd-d27555af0477.PNG)
![gpu](https://user-images.githubusercontent.com/17638040/71427265-c1f7c300-2684-11ea-867c-5303dec3879b.PNG)

**Comment by AccidentallyOnPurpose** [comment]
4-5GB of GPU, that's awesome

**Comment by Nalewa** [comment]
So I think we can close the issue know, once again: good job anon.

**Comment by Nalewa** [comment]
Or maybe something is wrong, now AI often gives empty text after my actions or the responses are too short and it tends to looping after circa 3 actions. I have default config.

**Comment by Meanmelter** [comment]
Do you have anything in .\data\stories? I pulled the one from thedung2 and have just been using that.

**Comment by AccidentallyOnPurpose** [comment]
Hmm I did change a bunch of stuff in action generation so that is quite possible. Before I was giving the model only the last part of the story, now I'm giving it the whole story.

I'll change devlop branch to use the old way of doing actions, if you give it a try, please give me feedback.

**Comment by Nalewa** [comment]
> Do you have anything in .\data\stories?
In .\data\ I have only some .py files and nothing more. I just cloned this github and downloaded torrent with model.
But before changes using Clover version on CPU I had a decent feedback from AI so maybe something changed

**Comment by AccidentallyOnPurpose** [comment]
The devlop2 branch now does the old way of suggesting actions, let me know what you think.

You can also play around with the code on line 174 or play.py. You can switch between the new way and old way by disabling lines using the python comment symbol "#". E.g. below the new way is commented out and the old way is disabled. 

```py
                    # New way
                    # action_prompt = story_manager.story_context()  # This should be within the loop as it has a random sampling element
                    # action_prompt[-1] += '\n>'

                    # # OLD way
                    action_prompt = (
                        story_manager.story.results[-1]
                        if story_manager.story.results
                        else "\nWhat do you do now?"
                    ) + "\n>"
```

It's also hard to know what's important here, because the model is a black box e.g. does adding a space after the "\n " matter? Who knows lol. All we know that formatting that it may have seen on the internet during training is better, as it will be more familiar.

**Comment by AccidentallyOnPurpose** [comment]
An anon also commented that they didn't like how suggestions came at you one by one. Easy to change, but what do all of you think?

**Comment by Meanmelter** [comment]
I like that idea, would it cause it to load faster? I kind of like how it looks when they generate one-by-one.

Also, I have not ran into the looping on the new action generation. I will test out removing my .\data\stories to see if it starts looking; I recall having this problem awhile ago.

**Comment by AccidentallyOnPurpose** [comment]
No it would be the same speed. Yeah, I like having something to look at too. I think the anon was just on a weird terminal that resized or something.

Awesome let me know. I appreciate the help!

**Comment by Nalewa** [comment]
>The devlop2 branch now does the old way of suggesting actions,

I don't see new changes in this branch.

According suggestions I like it, but I don't like how they appear, they can appear all at once or not at all.

**Comment by AccidentallyOnPurpose** [comment]
Ops pushed

**Comment by Nalewa** [comment]
just copy pasted 
```
                    # New way
                    # action_prompt = story_manager.story_context()  # This should be within the loop as it has a random sampling element
                    # action_prompt[-1] += '\n>'

                    # # OLD way
                    action_prompt = (
                        story_manager.story.results[-1]
                        if story_manager.story.results
                        else "\nWhat do you do now?"
                    ) + "\n>"
```
And it seems to work normally

**Comment by AccidentallyOnPurpose** [comment]
Nice, yeah that works

**Comment by Meanmelter** [comment]
Hey @AccidentallyOnPurpose I renamed the stories file. It gave me good suggestions so it looked like it worked anyways but any response gave looping errors.
![image](https://user-images.githubusercontent.com/17638040/71428328-29664080-268e-11ea-824e-05269059531b.png)

**Comment by AccidentallyOnPurpose** [comment]
Hmm looks like the new suggestion generation is not as good.

One last thing to try, is the new way with a lower temp. If you can be bothered. That means go to config.ini and try with `action-temp` as like 0.4 or something.

https://github.com/cloveranon/Clover-Edition/blob/master/config.ini#L50

I'll add comments to the config so those variables are clearer

**Comment by Nalewa** [comment]
Yes, the new suggestions are now purely random.

**Comment by Nalewa** [comment]
```
Traceback (most recent call last):
  File "play.py", line 332, in <module>
    play(generator)
  File "play.py", line 185, in play
    suggested_action = ai_player.get_action(action_prompt)
  File "play.py", line 108, in get_action
    prompt, generate_num=settings.getint('action-generate-num'), temperature=settings.getint('action-temp'))
  File "C:\Users\Atalanta Alter\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1301, in get
    fallback=fallback, **kwargs)
  File "C:\Users\Atalanta Alter\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "C:\Users\Atalanta Alter\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 808, in _get_conv
    **kwargs)
  File "C:\Users\Atalanta Alter\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '0.4'
```

**Comment by Meanmelter** [comment]
Here is what it does when I leave the stories file.

By the way, by "Also, I have not ran into the looping on the new action generation." I was referring to not the old one that you just reverted to (I think).
![image](https://user-images.githubusercontent.com/17638040/71428481-04260200-268f-11ea-8b6f-660195595c2a.png)
Since I am not having the issue with the stories folder I think that may be the issue. I can run a test with the old action generation if you wish.

**Comment by AccidentallyOnPurpose** [comment]
Ah ok! I'll go back to the old one since it seems to work for everyone

**Comment by Nalewa** [comment]
I am going to sleep so the next testing from me would be like in min 5 hours, cya later

**Comment by AccidentallyOnPurpose** [comment]
No worries, merry xmas
