### ISSUE TITLE
Incorrect saved filename

### ISSUE THREAD

**Issue by AIDungeonWiXAnon** [cloveranon/Clover-Edition#70]
https://github.com/cloveranon/Clover-Edition/blob/0afca27300c207afe8b2ef5ab8da1d3c2ffccca9/play.py#L180-L182
https://github.com/cloveranon/Clover-Edition/blob/0afca27300c207afe8b2ef5ab8da1d3c2ffccca9/play.py#L187

It appears that the following lines are causing any inputted filename starting with a permutation of `saves/` to be stripped incorrectly (e.g. `alsoasave` becomes `lsoasave`, `specificsave` becomes `pecificsave`) as per the following test case:
![image](https://user-images.githubusercontent.com/58319376/71771267-034a6700-2efe-11ea-8f15-04ea4b67b344.png)

**Comment by devfag** [comment]
This is fixed in my current PR. I incorrectly used `lstrip` to remove the save directory if somebody enters it. `lstrip` will strip until the characters don't match the given string
