### ISSUE TITLE
death and winning doesn't reset story

### ISSUE THREAD

**Issue by Hikari-Haru** [cloveranon/Clover-Edition#79]
When the game resets after a death or a win and you select a new prompt it loads the old story instead clearing it like it does with /menu

**Comment by Hikari-Haru** [comment]
When the game resets after a death or a win, when you select a new prompt it loads the old story instead clearing it like it does with /menu

**Comment by AIDungeonWiXAnon** [comment]
Appreciate the bug report @Hikari-Haru, we should have this fixed in short order.
