### ISSUE TITLE
print_formatted_text is not defined

### ISSUE THREAD

**Issue by AmoArt** [cloveranon/Clover-Edition#89]
Traceback (most recent call last):
  File "play.py", line 659, in <module>
    generator = get_generator()
  File "play.py", line 29, in get_generator
    "loading-message", end="\n\n"
  File "C:\_AIGame\AIDunPyTorch\Clover-Edition-master\
tput
    print_formatted_text(to_formatted_text(text1, col1
NameError: name 'print_formatted_text' is not defined

C:\_AIGame\AIDunPyTorch\Clover-Edition-master>PAUSE
Press any key to continue . . .

**Comment by MikkoMMM** [comment]
It's an issue with you not having the Prompt Toolkit library, but it's still enabled in the settings. A solution is in https://github.com/cloveranon/Clover-Edition/pull/88 but not yet integrated to master.

**Comment by devfag** [comment]
For now you can fix it in your game's config.ini by setting `prompt-toolkit` to `off`.

**Comment by AmoArt** [comment]
The problem solve itself.
I am not sure if this is what fixed but what I've done was pip install prompt-toolkit
