### ISSUE TITLE
Empty action not caught by conditional checks

### ISSUE THREAD

**Issue by AIDungeonWiXAnon** [cloveranon/Clover-Edition#92]
https://github.com/cloveranon/Clover-Edition/blob/7a342d599405f91b5a30a149a3c5e5dc05950480/play.py#L554-L564
If you attempt to enter a blank input (carriage return) after an invalid /remember it instead causes the game to do a newline, lock up, and then spit out whatever text was entered after recovering.
![image](https://user-images.githubusercontent.com/58319376/71811181-ac49ac80-3039-11ea-95c1-d5f2f333e7d2.png)

**Comment by devfag** [comment]
Is this on prompt toolkit, non-pt, or both?

**Comment by devfag** [comment]
Sounds to me like there's something in the input buffer. I'm at work but try fixing it with these steps if you want.

Add this function to utils:
```python
def flush_input():
    try:
        import msvcrt
        while msvcrt.kbhit():
            msvcrt.getch()
    except ImportError:
        import sys, termios
        termios.tcflush(sys.stdin, termios.TCIOFLUSH)
 ```
And in `input_line` at the very end, call it. See if that works.

**Comment by devfag** [comment]
I haven't been able to recreate the bug on my end. Are you using Powershell? Powershell is known to have some interesting bugs. I would test on Powershell but I have all of my terminals automatically route through cmder and can't seem to open powershell anymore.

**Comment by AIDungeonWiXAnon** [comment]
It's using Windows Terminal with a cmd instance and no prompt toolkit.
My PowerShell actually stopped working for me a bit ago (unrelated to Clover), and I haven't fiddled with fixing it so anything I do/post is through cmd inside of Windows Terminal.
The exact process I've used is the following:
* type `/remember <enter>`
* press `<enter>`
* cursor should drop one line below the input `> You `
* game will lock up temporarily
* game resumes attempting to enter whatever you entered during the lock up period

I've had to install prompt-toolkit onto conda for a project, but once I finish that I'll reset my conda and attempt to reproduce this again with a new instance of Windows Terminal. If I can confirm the reproducibility and we're unable to get it to reproduce on your cmder I'll self-assign and see if I can't track it done once I've got a bit of free time.

**Comment by devfag** [comment]
Ohh, sorry, I misunderstood the issue. I'll give it a try and see if flushing the input fixes it.

**Comment by devfag** [comment]
Hmm, okay I followed the steps and still couldn't recreate the issue.

**Comment by AIDungeonWiXAnon** [comment]
Strange... Maybe some other people can weigh in on the reproducibility? I'll see about trying to reproduce this again in the near future and tracking down the source of the problem, be that something about my configuration or the game itself.

**Comment by AIDungeonWiXAnon** [comment]
Confirming that this still happens on my machine with a fresh install of packages (no prompt-toolkit).
Additionally, the latest version removes the background text for error messages. Is that an intended change?

Self-assigning this to try and track it down; I'll implement your buffer flushing system and see if that fixes things @devfag.

**Comment by AIDungeonWiXAnon** [comment]
On closer inspection, it seems that attempting to enter a blank/just spaces input at all, regardless of a preceding command, will cause this bug.
Traced it to the following conditional code:
https://github.com/cloveranon/Clover-Edition/blob/5df9784fa35a23938bb9fb61734a5ede8554d5ae/play.py#L603
`...`
https://github.com/cloveranon/Clover-Edition/blob/5df9784fa35a23938bb9fb61734a5ede8554d5ae/play.py#L620
If the user enters a blank action, the elif will detect this correctly but there is no else statement to catch it; the game simply hands the invalid (i.e. blank) action over to the AI, and since none of the normal action programming ran it seemingly gets treated as a newline by the terminal.

I'm surprised this isn't causing issues on your system as well @devfag, it seems agnostic to terminal/UI mode.

Pull request inbound, the following code after the elif fixes things on my game:
```
else:
    output("Please enter a valid action.", "error")
    return
```

**Comment by devfag** [comment]
I'll add a "Continuing..." message and merge with my next PR. Glad we cleared this up.
