### ISSUE TITLE
convert_gpt2_model.py fails to convert Vanilla GPT-2 134m

### ISSUE THREAD

**Issue by devfag** [cloveranon/Clover-Edition#94]
_This is using the model taken from the OpenCYOAI wiki_

When I attempt to convert the 134m vanilla gpt2 tensorflow-based model to pytorch, I get the following error:
```python
Traceback (most recent call last):
  File "convert_gpt2_model.py", line 110, in <module>
    args.gpt2_checkpoint_path, args.full, args.gpt2_config_file, args.pytorch_dump_folder_path
  File "convert_gpt2_model.py", line 55, in convert_gpt2_checkpoint_to_pytorch
    config = GPT2Config.from_json_file(gpt2_config_file)
  File "D:\Program Files\Python\lib\site-packages\transformers\configuration_utils.py", line 215, in from_json_file
    dict_obj = json.loads(text)
  File "D:\Program Files\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It's pretty minor considering the model isn't very practical to use, but I wonder what's causing it nonetheless.

**Comment by cloveranon** [comment]
Are all the correct files in the directory? It needs a json file with the hyperparameter configuration. If not you can find another one. E.g the one provided with huggingface under `GPT2_PRETRAINED_CONFIG_ARCHIVE_MAP` https://github.com/huggingface/transformers/blob/master/src/transformers/configuration_gpt2.py

**Comment by devfag** [comment]
looks correct to me: 
![image](https://user-images.githubusercontent.com/59345616/72002942-6564de00-3216-11ea-8d8d-35f97345cd3f.png)

**Comment by Akababa** [comment]
Why are they all 1kb? Can you try to open one of the json files and see what's inside?

**Comment by devfag** [comment]
ah, encoder.json is in fact not a json file and contains some ill-formed xml data. the model hosted on mega must be broken
