### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by devfag** [cloveranon/Clover-Edition#96]
Some anon found the ASCII text generator used to make the original logo. Thought I would use it to make a new logo. Thoughts? https://i.gyazo.com/a611c58150cebbafa57ee32a8c5c3d39.png

**Comment by MikkoMMM** [comment]
It looks like you've implemented it already. Either way is fine by me, though the new logo is now smaller than it was.

**Comment by devfag** [comment]
I'll revert it if people dislike it. It's not as wide, which should be better for small (or half-width) terminals
